Sprint 2
realdmitrii/middle.messenger.praktikum.yandex pull request #2
Opened 2022-11-05 22:57 UTC by realdmitrii

Задание спринта 2 сделано по чек-листу
Дизайн нескольких страниц не успел сделать, к сожалению. Сосредоточился на технической части

2022-11-07 01:34 UTC, agadoev requested changes
привет, @realdmitrii 
Я посмотрел работу и отметил места, над которыми еще стоит поработать
Предложил вариант рефакторинга для валидации. Давай поправим это и двинемся дальше

2022-11-07 01:34 UTC, agadoev commented on src/components/avatar/avatar.ts
> +  }
почему бы здесь не возвращать так же boolean? если эти строки должны показывается на экране, то лучше их указывать в шаблоне в зависимости от props.online

2022-11-07 01:34 UTC, agadoev commented on src/components/chat-box/chat-box.ts
> +      usersData: usersData[0]["chatBox"]
довольно опасное место. Что будет, если массив будет пустым или не будет свойства chatBox?

2022-11-07 01:34 UTC, agadoev commented on src/components/input/input.ts
> +  type?: string;
тут лучше использовать union
```suggestion
  type: "number" | "email" и тд;
```

2022-11-07 01:34 UTC, agadoev commented on src/components/link/link.ts
> +  onClick?: () => void;
насколько я помню, обработчик события должен принимать в себя объект Event

2022-11-07 01:34 UTC, agadoev commented on src/components/message-box/message-box.ts
> +  time: string;
Подумай над тем, чтобы использовать для обработки времени тип Date. Если нужно вывести время в виде отформатированной строки, удобно будет написать функцию, например
```
const formattedTime = (time: Date): string => { /* some logic */ }
```

2022-11-07 01:34 UTC, agadoev commented on src/components/message-box/message-box.ts
> +  arrayMessages: string[];
не critical, но если переменная названа в множественном числе, то это уже намекает на то, что в ней содержится массив. array в названии кажется избыточным

2022-11-07 01:34 UTC, agadoev commented on src/components/message-box/message-box.ts
> +  private _classModifier1(): string {
использование чисел в названиях методов/переменных/классов - bad practice и скорее всего можно этот код порефакторить

2022-11-07 01:34 UTC, agadoev commented on src/components/users-board/users-board.ts
> +      goToProfilePage: () => {
а ты пробовал делать переход на другую страницу через тег ```<a href=""></a>```? Семантически так правильнее делать

2022-11-07 01:34 UTC, agadoev commented on src/pages/login/login.ts
> +  ["login", "false"],
почему false представлен в виду строки? Вообще, всегда, если в коде видишь что-то по типу флагов - это сигнал о том, что где-то можно провести рефакторинг

2022-11-07 01:34 UTC, agadoev commented on src/pages/profile/profile.ts
> +]);
на самом деле не ясно для чего создается этот Map. Давай либо дадим более поясняющее название, либо напишем комментарий о том, какую функцию выполняет этот код

2022-11-07 01:34 UTC, agadoev commented on src/services/HTTPTransport.ts
> +  return outcome;
выглядит довольно сложно, я бы упростил
```suggestion
  return "?" + Object
 .entries(data)
 .map(([key, value]) => `${key}=${value}`)
 .join("&")
```

2022-11-07 01:34 UTC, agadoev commented on src/services/HTTPTransport.ts
> +  timeout: number;
```suggestion
  method: METHODS;
  headers: Record<string, string>;
  data: unknown;
  timeout: number;
```

2022-11-07 01:34 UTC, agadoev commented on src/services/HTTPTransport.ts
> +}
Подумай над тем, чтобы использовать union вместо enum'a. Union не транспилируется в объект, как enum, и на не нужно дублировать код (сейчас для каждого элемента перечисления дублируется строка). Подробнее можно почитать [тут](https://stackoverflow.com/questions/40275832/typescript-has-unions-so-are-enums-redundant)

2022-11-07 01:34 UTC, agadoev commented on src/services/HTTPTransport.ts
> +  request = (url: string, options: Options, timeout = 5000) => {
timeout уже есть в объекте options. Сейчас его можно передать и через параметры, и через options. Давай оставим что-то одно.

2022-11-07 01:34 UTC, agadoev commented on src/services/helpers.ts
> +export function validate(name: string, str: string): string {
тут точно нужно рефакторить. Такой код будет очень сложно поддерживать из-за большого количество if'ов. Я предлагаю разбить эту функцию на множество небольших функций-валидаторов с такой вот сигнатурой:
```type ValidatorFn = (value: string): boolean```

либо же, если могут быть разные причины, почему поле неправильное, можно задать такую сигнатуру
```
type ValidationResult<Reasons> = {
 valid: boolean
 reason: Reasons
}
type ValidatorFn = <Reasons>(value: string): ValidationResult<Reasons>

type nameValidatorFn: ValidatorFn<"empty" | "latin numbers" ...>(name: string) => {
   if (str.length == 0)
    return {
      valid: false,
      reason: "empty"
    }

    if (!containsOnlySymbols(name))
      return { ... }
}
```
для каждого поля можно создать отдельную такую функцию. Строковых констант тут быть не должно, они должны описываться в компоненте. В компоненте вызывается validator 

В общем, предложенный мной подход носит более декларативный характер, попробуй реализовать это

2022-11-07 11:43 UTC, agadoev commented
P.S.
Я немого ошибся и принял работу у нас в системе. Давай все же поправим те моменты, которые я отметил

2022-11-21 10:28 UTC, realdmitrii commented
> P.S. Я немого ошибся и принял работу у нас в системе. Давай все же поправим те моменты, которые я отметил
Привет. Приболел тут малость... В течение пары дней всё сделаю

2022-11-21 16:38 UTC, realdmitrii commented on src/components/message-box/message-box.ts
> +  arrayMessages: string[];
соглашусь, что может быть, не совсем удачное название, но кроме Messages я имел в виду что будут другие объекты, например recievedMessages, deletedMessages, delayedMessages  и тд. 
Поэтому, с твоего позволения, оставлю так)

2022-11-21 16:56 UTC, realdmitrii commented on src/components/message-box/message-box.ts
> +  private _classModifier1(): string {
Учту. Исправил

2022-11-21 17:11 UTC, realdmitrii commented on src/components/users-board/users-board.ts
> +      goToProfilePage: () => {
я раньше так и делал, сейчас был учебный момент- чтобы большинство страниц моментально открывались, через рендер
goToProfilePage: () => {
        renderDOM(new ProfilePage());
      }

2022-11-21 19:14 UTC, realdmitrii commented on src/services/HTTPTransport.ts
> +  timeout: number;
в 11 строке сделал undefined, так как unknown выдавал ошибку в 83 строке: "Аргумент типа \"{}\" нельзя назначить параметру типа \"Document | XMLHttpRequestBodyInit | null | undefined\".",
	
PS также думаю еще можно сделать тип any

2022-11-21 20:10 UTC, agadoev commented
Привет)
Хорошо, поправляйся

2022-11-22 05:39 UTC, realdmitrii commented on src/components/input/input.ts
> +  type?: string;
предполагаю возможным "string" | "number" | "email" | "tel" | "password"

2022-11-22 06:48 UTC, realdmitrii commented on src/services/HTTPTransport.ts
> +}
согласен. так удобнее. переделал. 
Думаю подобную конструкцию( как была) используют много студентов, потому что она предложена в уроках и в тренажере)

2022-11-23 19:50 UTC, realdmitrii commented on src/components/avatar/avatar.ts
> +  }
переделал (уменьшил на 3 строки- мелочь, а приятно))

2022-11-23 20:37 UTC, realdmitrii commented on src/components/link/link.ts
> +  onClick?: () => void;
onClick?: (e: MouseEvent) => void

2022-11-23 20:38 UTC, realdmitrii commented on src/components/link/link.ts
> +  onClick?: () => void;
вроде так...

2022-11-23 20:53 UTC, realdmitrii commented on src/services/HTTPTransport.ts
> +  request = (url: string, options: Options, timeout = 5000) => {
удалил timeout'ы из options

2022-11-23 21:02 UTC, realdmitrii commented on src/components/message-box/message-box.ts
> +  time: string;
справедливое замечание. исправил тип на Date. но так как пока этот нюанс еще нигде дальше не используется, то функцию переформатирования оставим на будущее)

2022-11-23 21:27 UTC, realdmitrii commented on src/services/helpers.ts
> +export function validate(name: string, str: string): string {
@agadoev Алексей, не совсем понимаю, у тебя везде используется type... это опечатка вместо например const? или мне еще покурить ts?)

2023-01-23 21:18 UTC, closed without merging